config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #

  get 'about', to: 'welcome#about'
  get 'books', to: 'welcome#books'
  get 'book_treasure', to: 'welcome#book_treasure'
  get 'book_mortal_kombat', to: 'welcome#book_mortal_kombat'
  get 'book_return', to: 'welcome#book_return'
  get 'book_zero', to: 'welcome#book_zero'
  get 'book_fire', to: 'welcome#book_fire'
  get 'book_stories', to: 'welcome#book_stories'
  get 'book_twist', to: 'welcome#book_twist'
  get 'book_brick', to: 'welcome#book_brick'
  get 'book_vecherinka', to: 'welcome#book_vecherinka'
  get 'book_ne_rasskazivay', to: 'welcome#book_ne_rasskazivay'
  get 'book_common_people', to: 'welcome#book_common_people'
  get 'meeting', to: 'welcome#meeting'
  get 'news', to: 'welcome#news'
  get 'librarians', to: 'welcome#librarians'
  get 'read_free', to: 'welcome#read_free'
  get 'contacts', to: 'welcome#contacts'
  get 'audio_video', to: 'welcome#audio_video'

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  http_basic_authenticate_with name: Rails.application.credentials.admin_user, password: Rails.application.credentials.admin_pass, if: :admin_controller?

  def admin_controller?
    self.class < ActiveAdmin::BaseController
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.slim
doctype html
html lang="ru"
  head
    title = content_for?(:title) ? yield(:title) : 'Евгения Овчинникова, писательница'
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : "Пишу детективные триллеры"}"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"
    / = javascript_include_tag 'application'
    = javascript_pack_tag 'application'
    = render 'partials/google-analytics'
    link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet"
    link href="https://fonts.googleapis.com/css2?family=Podkova:wght@400;500;600;700;800&display=swap" rel="stylesheet"
    link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"
    / script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"
    / script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"

    - if Rails.env.production?
      script async="async" src="https://www.googletagmanager.com/gtag/js?id=G-GB0EVXNF0J"
      javascript:
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-GB0EVXNF0J');


      javascript:
        (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
        ym(85400275, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true,
            webvisor:true
        });
      noscript
        div
          img src="https://mc.yandex.ru/watch/85400275" style="position:absolute; left:-9999px;" alt=""

    / Favicon
    link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"
    link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"
    link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"
    link rel="manifest" href="/site.webmanifest"
    link rel="mask-icon" href="/safari-pinned-tab.svg" color="#e54059"
    meta name="msapplication-TileColor" content="#e54059"
    meta name="theme-color" content="#E54059"

    javascript:
        (function (r) {
            window.r46 = window.r46 || function () {
                (r46.q = r46.q || []).push(arguments)
            };
            var s = document.getElementsByTagName(r)[0], rs = document.createElement(r);
            rs.async = 1;
            rs.src = '//cdn.rees46.com/v3.js';
            s.parentNode.insertBefore(rs, s);
        })('script');
        // Init everything
        r46('init', "#{Rails.application.credentials.r46_api_key}");


  body
    script src="https://unpkg.com/swiper/swiper-bundle.min.js"
    - if flash[:notice]
      .alert.alert-success = notice
    - if flash[:alert]
      .alert.alert-warning = alert
    / = render 'partials/navbar'
    = yield
    = render "partials/footer"

app/views/partials/_contact.slim
.container-fluid.m-0.py-6
  .container
    .row
      .col.text-center
        h2.font-weight-bold.text-center Написать мне
        h4.font-weight-bold.text-center.text-primary • • •
    .row.justify-content-center
      .col-md-12.col-lg-10.text-center
        h3.font-weight-light = mail_to 'evgenia@ovchinnikova.ru'
          / a.btn.btn-lg.btn-primary.rounded-pill.px-4 href="mailto:evgenia@ovchinnikova.ru" role="button" target="_blank" Say Hello!

app/views/partials/_footer.slim
.container-fluid.py-5.eo-footer
  .container
    .d-none.d-lg-flex.justify-content-between.pb-5
      a.eo-link-footer href='/' Главная
      a.eo-link-footer href='about' Обо мне
      a.eo-link-footer href='books' Книги
      / a.eo-link-footer href='meeting' Встречи
      / a.eo-link-footer href='news' Новости
      a.eo-link-footer href='librarians' Библиотекарям и учителям
      a.eo-link-footer href='read_free' Читать бесплатно
      a.eo-link-footer href='contacts' Контакты

    .d-none.d-lg-flex.justify-content-between
      .d-flex.flex-column.eo-text-footer
        .small © #{Time.now.year}, Евгения Овчинникова
        .small Все права защищены.
      .d-flex
        / .ml-3
        /   a.eo-icon-footer href='https://www.facebook.com/writer.ovchinnikova' target='_blank'
        /     i.fab.fa-facebook-f.fa-lg
        .ml-3
          a.eo-icon-footer href='https://vk.com/e.ovchinnikova ' target='_blank'
            i.fab.fa-vk.fa-lg
        / .ml-3
          a.eo-icon-footer href='https://www.instagram.com/evgenia_ovchinnikova_writer/' target='_blank'
            i.fab.fa-instagram.fa-lg

    .d-flex.d-lg-none.justify-content-center.py-4
      .flex-column.justify-content-center
        .d-flex.justify-content-center.mb-4
          = link_to image_tag('logo/eo-logo-footer.svg'), '/', class:"img-fluid"
        .d-flex.justify-content-center.mb-4
          / .p-3
          /   a.eo-icon-footer href='https://www.facebook.com/writer.ovchinnikova' target='_blank'
          /     i.fab.fa-facebook-f.fa-2x
          .p-3
            a.eo-icon-footer href='https://vk.com/e.ovchinnikova ' target='_blank'
              i.fab.fa-vk.fa-2x
          / .p-3
            a.eo-icon-footer href='https://www.instagram.com/evgenia_ovchinnikova_writer/' target='_blank'
              i.fab.fa-instagram.fa-2x
        .d-flex.flex-column.text-center.eo-text-footer
          .small © #{Time.now.year}, Евгения Овчинникова
          .small Все права защищены.

app/views/partials/_google-analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-4022494-5"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-4022494-5');
</script>

app/views/partials/_meeting.slim
.container-fluid.eo-section-fluid
  .container.eo-section
    .row.mb-4
      .col.text-center
        h2 Встречи
        h4.font-weight-bold.text-center.text-primary • • •
    .row
      .col-2.text-center
        .bg-primary.text-white.p-3.mb-3
          h1.display-4.mb-0 14
          h6.small Сентября
        h6 Начало
        h6 в 16:00
      .col-10
        div.text-primary Екатеринбург
        h3 Творческая встреча с автором
        p.small ул. Горького 4 А, Музей архитектуры и дизайна УрГАХУ, Зал библиотеки
        p Друзья, в ближайшие выходные я приезжаю в Екатеринбург, на фестиваль "Книжный полоз". Приглашаю на встречу!
        p И посмотрите, фестиваль хороший, много интересных людей будет.
        a.btn.btn-outline-primary.px-3 href="meeting" role="button" Подробнее →

app/views/partials/_navbar.slim
.container-fluid.eo-navbar
  .container
    .nav.navbar.navbar-expand-lg.p-0.m-0
      .navbar-brand.p-0.m-0 = link_to image_tag('logo/eo-logo-color.svg', alt:'На главную', class:'eo-navbar-logo'), '/'

      // Hamburger Icon v2
      button.p-0.m-0 class="navbar-toggler navbar-toggler-right collapsed eo-navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
        span class="close"
          = image_tag 'icons/navbar/close.svg'
        span class="eo-navbar-toggler-icon"
          = image_tag 'icons/navbar/hamburger.svg'

      .collapse.navbar-collapse id="navbarSupportedContent"
        ul.navbar-nav.mr-auto
          - if !(defined? active) || active == "about"
            li.nav-item.active.eo-navbar-item.eo-navbar-item-active
              a.nav-link.eo-navbar-link href='about' Обо мне
          - else
            li.nav-item.active.eo-navbar-item
              a.nav-link.eo-navbar-link href='about' Обо мне

          - if !(defined? active) || active == "books"
            li.nav-item.active.eo-navbar-item.eo-navbar-item-active
              a.nav-link.eo-navbar-link href='books' Книги
          - else
            li.nav-item.active.eo-navbar-item
              a.nav-link.eo-navbar-link href='books' Книги

          / - if !(defined? active) || active == "meeting"
          /   li.nav-item.active.eo-navbar-item.eo-navbar-item-active
          /     a.nav-link.eo-navbar-link href='meeting' Встречи
          / - else
          /   li.nav-item.active.eo-navbar-item
          /     a.nav-link.eo-navbar-link href='meeting' Встречи

          / - if !(defined? active) || active == "news"
          /   li.nav-item.active.eo-navbar-item.eo-navbar-item-active
          /     a.nav-link.eo-navbar-link href='news' Новости
          / - else
          /   li.nav-item.active.eo-navbar-item
          /     a.nav-link.eo-navbar-link href='news' Новости

          - if !(defined? active) || active == "librarians"
            li.nav-item.active.eo-navbar-item.eo-navbar-item-active
              a.nav-link.eo-navbar-link href='librarians' Библиотекарям и учителям
          - else
            li.nav-item.active.eo-navbar-item
              a.nav-link.eo-navbar-link href='librarians' Библиотекарям и учителям

          - if Post.exists?
            - if !(defined? active) || active == "news"
              li.nav-item.active.eo-navbar-item.eo-navbar-item-active
                a.nav-link.eo-navbar-link href='/news' Новости
            - else
              li.nav-item.active.eo-navbar-item
                a.nav-link.eo-navbar-link href='/news' Новости

          - if !(defined? active) || active == "read_free"
            li.nav-item.active.eo-navbar-item.eo-navbar-item-active
              a.nav-link.eo-navbar-link href='read_free' Бесплатно
          - else
            li.nav-item.active.eo-navbar-item
              a.nav-link.eo-navbar-link href='read_free' Бесплатно

          - if !(defined? active) || active == "audio_video"
            li.nav-item.active.eo-navbar-item.eo-navbar-item-active
              a.nav-link.eo-navbar-link href='audio_video' Аудио и ТВ
          - else
            li.nav-item.active.eo-navbar-item
              a.nav-link.eo-navbar-link href='audio_video' Аудио и ТВ

          - if !(defined? active) || active == "contacts"
            li.nav-item.active.eo-navbar-item.eo-navbar-item-active
              a.nav-link.eo-navbar-link href='contacts' Контакты
          - else
            li.nav-item.active.eo-navbar-item
              a.nav-link.eo-navbar-link href='contacts' Контакты

        .my-4
          = render('partials/share_navbar')


/ .container-fluid.eo-navbar
/   .container
/     .nav.navbar.navbar-expand-lg.p-0.m-0
/       .navbar-brand.p-0.m-0 = link_to image_tag('logo/eo-logo-color.svg', alt:'На главную', class:'eo-navbar-logo'), '/'
/
/       // Hamburger Icon v2
/       button.p-0.m-0 class="navbar-toggler navbar-toggler-right collapsed eo-navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
/         span class="close"
/           = image_tag 'icons/navbar/close.svg'
/         span class="eo-navbar-toggler-icon"
/           = image_tag 'icons/navbar/hamburger.svg'
/
/       .collapse.navbar-collapse id="navbarSupportedContent"
/         ul.navbar-nav.mr-auto
/           li.nav-item.active.eo-navbar-item.eo-navbar-item-active
/             a.nav-link.eo-navbar-link href='about' Обо мне
/           li.nav-item.eo-navbar-item
/             a.nav-link.eo-navbar-link href='books' Книги
/           li.nav-item.eo-navbar-item
/             a.nav-link.eo-navbar-link href='meeting' Встречи
/           li.nav-item.eo-navbar-item
/             a.nav-link.eo-navbar-link href='news' Новости
/           li.nav-item.eo-navbar-item
/             a.nav-link.eo-navbar-link href='librarians' Библиотекарям и учителям
/           li.nav-item.eo-navbar-item
/             a.nav-link.eo-navbar-link href='read_free' Бесплатно
/           li.nav-item.eo-navbar-item
/             a.nav-link.eo-navbar-link href='contacts' Контакты
/
/         = render('partials/share_navbar')



    / .nav.navbar.navbar-expand-lg.navbar-light.eo-navbar
    /   .navbar-brand
    /     = link_to image_tag('logo/eo-logo-color.svg'), '/', class:"d-block eo-navbar-logo"
    /   button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    /     span class="text-primary"
    /       i.fas.fa-bars.fa-lg
    /   .collapse.navbar-collapse id="navbarSupportedContent"
    /     ul.navbar-nav.mr-auto
    /       li.nav-item.active
    /         a.nav-link href='about' Обо мне
    /       li.nav-item
    /         a.nav-link href='books' Книги
    /       li.nav-item
    /         a.nav-link href='meeting' Встречи
    /       li.nav-item
    /         a.nav-link href='news' Новости
    /       li.nav-item
    /         a.nav-link href='librarians' Библиотекарям и учителям
    /       li.nav-item
    /         a.nav-link href='read_free' Читать бесплатно
    /       li.nav-item
    /         a.nav-link href='contacts' Контакты

app/views/partials/_reviews.slim
.container-fluid.eo-section-fluid.eo-bg-gray
  .container.eo-section.py-6
    .row
      .col
          h2 Отзывы
          div.my-6
            .d-flex.my-4.align-items-center
              .d-flex.text-center.eo-icon-author.mr-3.align-items-center.justify-content-center
                div.text-light A
              .d-flex.flex-column
                .lead.mb-2 awesome.tatianuschck4
                .text-muted 29 октября, 6:07
            p Книга «Мортал комбат и другие 90-е» начинающей писательницы Евгении Овчинниковой рассказывает о ее детстве в то противоречивое время. С первой страницы эти рассказы, пронизанные доброй ностальгией, хватают за жабры и не отпускают до конца.
            p Каждый рассказ – это определенный этап взросления главной героини. Вот девочка Женя ловит сбежавшую корову из деревни, собирает вкладыши из жвачки «Турбо» и режется в «Мортал комбат», а вот она уже задумывается о более взрослых вещах и пытается посмотреть «Эммануэль».

          hr
          div.my-6
            .d-flex.my-4.align-items-center
              .d-flex.text-center.eo-icon-author.mr-3.align-items-center.justify-content-center
                div.text-light A
              .d-flex.flex-column
                .lead.mb-2 awesome.tatianuschck4
                .text-muted 29 октября, 6:07
            p Книга «Мортал комбат и другие 90-е» начинающей писательницы Евгении Овчинниковой рассказывает о ее детстве в то противоречивое время. С первой страницы эти рассказы, пронизанные доброй ностальгией, хватают за жабры и не отпускают до конца.
            p Каждый рассказ – это определенный этап взросления главной героини. Вот девочка Женя ловит сбежавшую корову из деревни, собирает вкладыши из жвачки «Турбо» и режется в «Мортал комбат», а вот она уже задумывается о более взрослых вещах и пытается посмотреть «Эммануэль».
            p В книге настоящее и прошлое тесно переплетаются. К Жене приезжает племянник, который случайно находит ее рукописи о детстве, и с этого начинается все повествование. Потом мы полностью погружаемся в лихие 90-е и лишь изредка возвращаемся в наше время, чтобы сравнить и решить, действительно ли раньше было лучше.

            hr
            div.my-6
              .d-flex.my-4.align-items-center
                .d-flex.text-center.eo-icon-author.mr-3.align-items-center.justify-content-center
                  div.text-light A
                .d-flex.flex-column
                  .lead.mb-2 awesome.tatianuschck4
                  .text-muted 29 октября, 6:07
              p Книга «Мортал комбат и другие 90-е» начинающей писательницы Евгении Овчинниковой рассказывает о ее детстве в то противоречивое время. С первой страницы эти рассказы, пронизанные доброй ностальгией, хватают за жабры и не отпускают до конца.

app/views/partials/_share_book.slim
.mb-6
  h5.mb-4 Поделиться:
  .d-flex
    a href='/'
      .d-flex.align-items-center.eo-icon-share.justify-content-center.mr-2
        i.fab.fa-facebook-f.fa-lg
    a href='/'
      .d-flex.align-items-center.eo-icon-share.justify-content-center.mr-2
        i.fab.fa-vk.fa-lg
    a href='/'
      .d-flex.align-items-center.eo-icon-share.justify-content-center
        i.fab.fa-instagram.fa-lg

app/views/partials/_share_navbar.slim
.d-none.d-md-flex
  a.ml-2 href='https://www.facebook.com/writer.ovchinnikova' target='_blank'
    .d-flex.p-3.align-items-center.eo-icon-share-small.justify-content-center
      i.fab.fa-facebook-f.fa-sm
  a.ml-2 href='https://vk.com/eugenia_ovchinnikova' target='_blank'
    .d-flex.p-3.align-items-center.eo-icon-share-small.justify-content-center
      i.fab.fa-vk.fa-sm
  / a.ml-2 href='https://www.instagram.com/evgenia_ovchinnikova_writer/' target='_blank'
    .d-flex.p-3.align-items-center.eo-icon-share-small.justify-content-center
      i.fab.fa-instagram.fa-sm

.d-flex.d-md-none
  a.mr-3 href='https://www.facebook.com/writer.ovchinnikova' target='_blank'
    .d-flex.align-items-center.eo-icon-share.justify-content-center
      i.fab.fa-facebook-f.fa-lg
  a.mr-3 href='https://vk.com/eugenia_ovchinnikova' target='_blank'
    .d-flex.align-items-center.eo-icon-share.justify-content-center
      i.fab.fa-vk.fa-lg
  / a href='https://www.instagram.com/evgenia_ovchinnikova_writer/' target='_blank'
    .d-flex.align-items-center.eo-icon-share.justify-content-center
      i.fab.fa-instagram.fa-lg

app/views/partials/_slides.slim
a href="#{book_url}"
  .container-fluid class="eo-carousel-bg eo-carousel-bg-#{background}"
    .container
      .row.align-items-center.d-none.d-md-flex
        .col.text-light
          h1.display-4 = title.html_safe
        .col
          = image_tag("#{book_image_url}", alt:"#{title}", class:"img-fluid eo-carousel-book")
      .d-flex.d-md-none.justify.content-center
        .col.text-light.text-center
          h1.my-6 = title.html_safe
          = image_tag("#{book_image_url}", alt:"#{title}", class:"img-fluid eo-carousel-book")



          / = link_to image_tag("#{book_image_url}", alt:"#{title}", class:"img-fluid eo-carousel-book"), "#{book_url}"


/ = link_to image_tag('books/brick.jpg', alt:"Мортал комбат и другие 90-е", class:"d-block w-100"), 'books'

app/views/partials/_subscription.slim
.container-fluid.eo-section-fluid
  .container.eo-section-bottom
    .row.justify-content-center
      .col-12.col-md-8.text-center
        h2.font-weight-bold Подписаться на новости
        h4.font-weight-bold.text-primary • • •
        p.lead.mb-5 Лучший способ быть в курсе последних событий. Оставляйте свой email и получайте самые свежие новости на почту.

        .alert.alert-success.d-none#subscribedmessage Спасибо! Теперь вы в списке.

        form#subscribemailing
          div class="input-group input-group-lg"
            div class="input-group-prepend"
              span class="input-group-text" id="addon-wrapping"
                i.fas.fa-envelope.fa-1x.p-0.m-0
            input#subscribemailingfield type="email" class="form-control" placeholder="Ваш email" aria-label="Username" aria-describedby="addon-wrapping" name="email"
            div.d-none.d-md-flex class="input-group-append"
              input class="btn btn-primary" type="submit" id="button" value="Подписаться"

            div.d-flex.d-md-none.my-3 class="input-group"
              input class="btn btn-lg btn-primary eo-btn-cta" type="submit" id="button" value="Подписаться"

        / form action="" method="post" target="_blank"
        /   .form-row.mb-4
        /     .col-md-6.ml-auto.mb-3
        /       .input-group.input-group-lg.z-depth-1
        /         .input-group-prepend
        /           span.input-group-text
        /             i class="fa fa-envelope"
        /         .input type="email" name="EMAIL" class="form-control form-control-lg rgba-white-light white-text border-0 z-depth-0" placeholder="Email Address"
        /     .col-md-2.mr-auto
        /       button.btn.btn-lg.btn-primary.eo-btn-cta Subscribe

        / .social.text-center.py-4
        /   a.mx-4 href='https://www.facebook.com/writer.ovchinnikova' target='_blank'
        /     i.fab.fa-facebook-f.fa-2x
        /   a.mx-4 href='https://vk.com/eugenia_ovchinnikova' target='_blank'
        /     i.fab.fa-vk.fa-2x
        /   a.mx-4 href='https://www.instagram.com/evgenia_ovchinnikova_writer/' target='_blank'
        /     i.fab.fa-instagram.fa-2x

app/views/partials/_swiper_book_unit.slim
.d-flex.h-100.justify-content-center.text-center
  .d-flex.flex-column.p-3
    .mb-4
      = image_tag "books/#{book_cover}.jpg", class: 'img-fluid eo-shadow-card-lg'
    .d-flex.flex-column.px-2
      a href="/#{book_link}"
        h3 = book_title.html_safe
      .text-muted.mb-1  = book_description.html_safe
    .mt-auto.py-3 = link_to "#{book_button} →", "/#{book_link}", class: ''

app/views/welcome/audio_video.slim
- content_for :title, 'Аудио и ТВ – Евгения Овчинникова, писательница'

= render'partials/navbar',
        active: "audio_video"

.container-fluid.eo-section-fluid
  .container.eo-section-header
    .row
      .col-12
        h1 Аудио и ТВ
        nav.eo-navbar-breadcrumb aria-label="breadcrumb"
          ol.p-0.eo-bg-transparent class="breadcrumb"
            li class="breadcrumb-item"
              a href="/" Главная
            li class="breadcrumb-item active" aria-current="page" Аудио и ТВ

  .container.eo-section
    .row
      .col
        hr
        .px-md-3.py-3
          .mb-2
            a href="https://www.kinoafisha.info/series/6287/" target='blank'
              .h3 Дурная кровь. Сериал. Мелодрама, мистика. ТВ3.
            .text-dark Главный герой, Максим, получил в наследство от матери ведьмовской дар. История двух поколений на фоне борьбы добра и зла.
          div
            a href="https://www.kinoafisha.info/series/6287/" target='blank' class="btn btn-primary" Страница сериала на Киноафише
        hr
        .px-md-3.py-3
          .mb-2
            a href="https://www.storytel.com/ru/ru/books/2042928-Chemodan" target='blank'
              .h3 Чемодан. Аудиоспектакль на Storytel. Ужасы, детектив, триллер. Входит в сборник "Если вы слышите эту запись...".
            .text-dark Когда мне было пять лет, маме дали квартиру "от государства". Квартира оказалась разгромленная, поэтому вся родня собралась, чтобы помочь нам расхламиться. Когда большая часть бардака была отправлена в мусорные баки, дядя Миша полез выгребать хлам на антресоли. Оттуда он достал дипломат (который черный, с металлическими заклепками), заглянул в него, потом бросился в ванную и его долго рвало. После он молча вышел из квартиры и унес дипломат на дальнюю мусорку. С тех пор прошло 32 года, и мы до сих пор не знаем, что было внутри. Я дописала эту историю, и получился "Чемодан".
          div
            a href="https://www.storytel.com/ru/ru/books/2042928-Chemodan" target='blank' class="btn btn-primary" Слушать
        hr
        .px-md-3.py-3
          .mb-2
            a href="https://youtu.be/DaEJAVs2owY" target='blank'
              .h3 Люди в окне. Ужасы, триллер. ТВ-3 Dark. Входит в антологию "Страшные истории".
            .text-dark Екатеринбург. Случайная ночевка в заброшенном доме в лесу приводит к страшным событиям. Всю ночь с улицы сквозь закрытое окно кто-то смотрел на неудачливого охотника. Уехав, он сам привёл их в город и к своему дому. А они каждую ночь смотрят и ждут. Но чего?
          a href="https://youtu.be/DaEJAVs2owY" target='blank' class="btn btn-primary" Смотреть
        hr


= render "partials/subscription"